// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Bnxcnw1W6JG23-PFKd23ZCVdrFAYDjw',
    appId: '1:181206015493:web:5694857bbac9f940b6866c',
    messagingSenderId: '181206015493',
    projectId: 'customer-c538e',
    authDomain: 'customer-c538e.firebaseapp.com',
    storageBucket: 'customer-c538e.firebasestorage.app',
    measurementId: 'G-C35DLDVXTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsR9wEaYHs3srbT_8ClvxYzPvhNKdIH3U',
    appId: '1:181206015493:android:a878c36f966f9c47b6866c',
    messagingSenderId: '181206015493',
    projectId: 'customer-c538e',
    storageBucket: 'customer-c538e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUjigPzp0d0y-XDksXcLa5bPds763Ip4',
    appId: '1:181206015493:ios:6f502364e1f45eadb6866c',
    messagingSenderId: '181206015493',
    projectId: 'customer-c538e',
    storageBucket: 'customer-c538e.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUjigPzp0d0y-XDksXcLa5bPds763Ip4',
    appId: '1:181206015493:ios:6f502364e1f45eadb6866c',
    messagingSenderId: '181206015493',
    projectId: 'customer-c538e',
    storageBucket: 'customer-c538e.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Bnxcnw1W6JG23-PFKd23ZCVdrFAYDjw',
    appId: '1:181206015493:web:8fedbd0bbd3f8c38b6866c',
    messagingSenderId: '181206015493',
    projectId: 'customer-c538e',
    authDomain: 'customer-c538e.firebaseapp.com',
    storageBucket: 'customer-c538e.firebasestorage.app',
    measurementId: 'G-YMBSFW0BGE',
  );

}